version: "3.9"

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis-cluster-single
    ports:
      - "6379:6379"
    volumes:
      - ./redis-cluster.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
